- name: Fetch Firmware Details
  hosts: apic
  gather_facts: no

  vars:
    aci_login: &aci_login
      hostname: '{{ apic_host }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password | regex_escape() }}'
      use_proxy: '{{ apic_use_proxy }}'
      validate_certs: '{{ apic_validate_certs }}'

  vars_files:
          - vars.yml
  tasks: 

  - name: Query APIC
    aci_rest:
     <<: *aci_login
     method: get
     path: "{{ api_path.firmware_nodes }}"
    delegate_to: localhost     
    register: result

  - name: Filter Query
    set_fact:
      LEAF_FIRMWARE: "{{ result | json_query(\"imdata[*].fabricNode.attributes | [?role=='leaf'].{name: name, model: model, version: version}\") }}"
      SPINE_FIRMWARE: "{{ result | json_query(\"imdata[*].fabricNode.attributes | [?role=='spine'].{name: name, model: model, version: version}\") }}" 
      CONTROLLER_FIRMWARE: "{{ result | json_query(\"imdata[*].fabricNode.attributes | [?role=='controller'].{name: name , model: model, version: version}\") }}"

  - name: APIC FIRMWARE DETAILS
    debug:
     var:  CONTROLLER_FIRMWARE

  - name: SPINE FIRMWARE DETAILS
    debug:
     var: SPINE_FIRMWARE

  - name: LEAF FIRMWARE DETAILS
    debug:
     var: LEAF_FIRMWARE

